### ISSUE TITLE
[EmitPy] main_const_eval_* signatures require a device parameter that consteval__main never passes (tt-xla path)

### ISSUE THREAD

**Issue by mvasiljevicTT** [tenstorrent/tt-mlir#8498]
Sub-issue of #8494.

## Context

Hit while bringing up codegen_py for the DeepSeek V3.2 decode graph on a 4×8 Blackhole galaxy. **Does not reproduce** under standalone `tt-alchemist generate-python` on the captured `ttnn_<ts>.mlir` snapshot — only via the tt-xla → tt-alchemist invocation path. See parent for the full emit recipe and attached IR.

## Evidence

Via the tt-xla codegen-py path, every emitted const-eval function takes `device` as a required positional parameter:

```python
def main_const_eval_47(arg_0, device):
    ...
```

`consteval__main` calls them without one:

```python
main_const_eval_47_0 = main_const_eval_47(
    [weights["model.transformer.layers.1.ffn.mlp.experts.down_proj"]]
)
```

Result: `TypeError: main_const_eval_47() missing 1 required positional argument: 'device'` at the first call. `_main` does not run. On this graph, 55 const-eval functions are affected.

## Path divergence

Running `tt-alchemist generate-python` on the same `ttnn_<ts>.mlir` snapshot yields const-evals that drop the `device` parameter entirely and inline `utils.DeviceGetter.get_device((4, 8))` in each body — that form runs cleanly. So the bug surfaces only on the tt-xla → tt-alchemist invocation path. Most likely cause is a pipeline option (or split-files / `FileOp` codegen mode) that toggles const-eval to a `device`-parameter form on one path and not the other, and leaves the call sites in their original shape. This is the part worth triaging before picking a fix.

## Proposed fix

Once the path divergence is understood, either:

- thread `device` through every call site in `consteval__main`, or
- emit each const-eval with a `device=None` default plus a `utils.DeviceGetter.get_device(<mesh_shape>)` fallback inside the body — matching what standalone tt-alchemist already does.

**Comment by amilovanovicTT** [comment]
(tldr) This will be fixed once the #8386 lands and is propagated in ttmlit->ttxla uplift.

This issue is caused by #8323, which was a hotfix for the conflict that arises when the `TTNNCreateMainForTest` pass is performed (it is under the option `createMainForTest`). The hotfix just skips to perform  `TTNNCreateMainForTest` pass on the forward functions, whose input arguments were split into activations and weights, leaving those forward functions and consequently their consteval wrapper functions without the device argument. On the other hand, when `createMainForTest` option is set to true, a device argument is injected into the consteval functions' signatures. 
Since `createMainForTest` option is set to true by default in tt-xla, `main` and `consteval_main` are missing the device argument, and all `main_const_eval_*`  require a device argument.

**Comment by svuckovicTT** [comment]
Closing as #8386 has landed (should be picked up after the next tt-xla uplift).
